// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC61fEU5-SjGYmmqiJUBykHgjI0FszKSjA',
    appId: '1:4856728982:web:275e83fb64e293e3b6e1b7',
    messagingSenderId: '4856728982',
    projectId: 'sneakerspace-204ee',
    authDomain: 'sneakerspace-204ee.firebaseapp.com',
    storageBucket: 'sneakerspace-204ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqQIxtNDmT2A2H0sA2LS_sgzaK0sAzXlY',
    appId: '1:4856728982:android:2cafbf2312a333f6b6e1b7',
    messagingSenderId: '4856728982',
    projectId: 'sneakerspace-204ee',
    storageBucket: 'sneakerspace-204ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS8QXDXkJfilWCsoJv9dPkfYK6NPDOIRI',
    appId: '1:4856728982:ios:31eb575af2829f60b6e1b7',
    messagingSenderId: '4856728982',
    projectId: 'sneakerspace-204ee',
    storageBucket: 'sneakerspace-204ee.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS8QXDXkJfilWCsoJv9dPkfYK6NPDOIRI',
    appId: '1:4856728982:ios:31eb575af2829f60b6e1b7',
    messagingSenderId: '4856728982',
    projectId: 'sneakerspace-204ee',
    storageBucket: 'sneakerspace-204ee.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC61fEU5-SjGYmmqiJUBykHgjI0FszKSjA',
    appId: '1:4856728982:web:007659489ac2d3ebb6e1b7',
    messagingSenderId: '4856728982',
    projectId: 'sneakerspace-204ee',
    authDomain: 'sneakerspace-204ee.firebaseapp.com',
    storageBucket: 'sneakerspace-204ee.appspot.com',
  );
}
